/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs261;
import java.sql.*;
import java.util.*;


import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    private Connection connection;
    private DBConnection db;

    @Test
    public Boolean TestcreateUser() throws SQLException {
        User u = new User("jiayi","Xu","996616811@qq.com");
        db.createUser(u, "210", "012");
        String query = "SELECT * FROM USER WHERE email = '996616811@qq.com'"+
                        " AND phash = '210' AND fname = 'jiayi' AND lname = 'Xu' AND salt = '012'";
        PreparedStatement stmt = connection.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();
        if(rs.next()){
            return true;
        }
        return false;
    }
    
    public Boolean TestverifyPassword() throws SQLException{
        User u = new User("jiayi","Xu","996616811@qq.com");
        db.createUser(u, "210", "012");
        User t1 = db.verifyPassword("996616811@qq.com", "210");
        User t2 = db.verifyPassword("996616811@qq.com", "110");
        User t3 = db.verifyPassword("000000000@qq.com", "210");
        if((t1.getLname()==u.getLname())&&(t1.getFname()==u.getFname())){
            if ((t2==null)&&(t3==null)) {
                return true;
            }
        }
        return false;
    }

    public Boolean TestcreateSession() throws SQLException{
        User u = new User("jiayi","Xu","996616811@qq.com");
        db.createUser(u, "210", "012");
        HostSesh s = new HostSesh("ABCDEF", "ABC123", "test", u, "ABCDEF");
        db.createSession(s);
        String query = "SELECT userID FROM SESH WHERE id = 'ABCDEF'"+
                        " AND seriesID = 1 AND sname = 'test' AND secure = 'ABCDEF'";
        PreparedStatement stmt = connection.prepareStatement(query);
        ResultSet rs = stmt.executeQuery();
        if(rs.next()){
            String query2 = "SELECT * FROM USER WHERE id = ?"+
                            " AND fname = 'jiayi' AND lname = 'Xu'";
            PreparedStatement stmt2 = connection.prepareStatement(query2);
            stmt2.setInt(1, rs.getInt(1));
            ResultSet rs2 = stmt.executeQuery();
            if (rs2.next()){
                return true;
            }
        }
        return false;
    }

    @Test void appHasAGreeting() {
        //App classUnderTest = new App();
        //assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}

