/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package cs261;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    /*cs261.Analyse an = new cs261.Analyse();
    @Test
    void pythonScript() throws Exception {
        String x = an.scriptRun();
        assertTrue(x.equals("Hello World!"));
    }*/
}
